force-app/main/default/objects/Account/fields/Purchase_Order_Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Available_Credit__c</fullName>
    <formula>Purchase_Order_Credit_Limit__c - Purchase_Order_Used_Credit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Order Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_Order_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Credit_Limit__c</fullName>
    <label>Purchase Order Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_Order_Used_Credit__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Used_Credit__c</fullName>
    <label>Purchase Order Used Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DealerCreditController.cls
public with sharing class DealerCreditController {

    @AuraEnabled(cacheable=true)
    public static Account getDealerCredit() {

        String userEmail = UserInfo.getUserEmail();

        System.debug('CURRENT USER EMAIL = ' + userEmail);

        List<Contact> contacts = [
            SELECT Id, Email, AccountId, Account.Name
            FROM Contact
            WHERE Email = :userEmail
            AND AccountId != null
            LIMIT 1
        ];

        System.debug('CONTACTS FOUND = ' + contacts);

        if (contacts.isEmpty()) {
            System.debug('NO CONTACT FOUND FOR EMAIL');
            return null;
        }

        Id accountId = contacts[0].AccountId;

        System.debug('ACCOUNT ID = ' + accountId);

        Account dealerAccount = [
            SELECT Id,
                   Name,
                   Purchase_Order_Credit_Limit__c,
                   Purchase_Order_Used_Credit__c,
                   Purchase_Order_Available_Credit__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];

        System.debug('DEALER ACCOUNT = ' + dealerAccount);
        System.debug('CREDIT LIMIT = ' + dealerAccount.Purchase_Order_Credit_Limit__c);
        System.debug('USED CREDIT = ' + dealerAccount.Purchase_Order_Used_Credit__c);
        System.debug('AVAILABLE CREDIT = ' + dealerAccount.Purchase_Order_Available_Credit__c);

        return dealerAccount;
    }
}